# infrastructure/k8s/prod/langgraph-data-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langgraph-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
